### ISSUE TITLE
Q: How to use this for a carousel?

### ISSUE THREAD

**Issue by datakurre** [collective/collective.portlet.fullview#1]
@thet, I think, this works properly with collective.panels, but would you have time to describe once more, how did you use this for a carousel?

It seems that I'm not familiar enough, how the normal fullview works.

Currently, for me c.p.fullview renders only "folder listing" view of a target folder and only when the folder has the default view as its default view. If I change the default view of the folder, portlet stops rendering any content. Is this the correct behavior of c.p.fullview, or am I missing something?

![nayttokuva 2015-03-16 kello 21 54 40](https://cloud.githubusercontent.com/assets/160447/6675118/1ff76216-cc27-11e4-9dcc-33f7e2610bde.png)

**Comment by datakurre** [comment]
Oh, I was using bad example content (not default image type). So, now the default folder full view properly displays previews for images, but the portlet still displays only folder listing (and if I change the folder default view to something else than the default view [folder_listing] the portlet remains completely empty).

**Comment by thet** [comment]
i hope i don't lead you on a wrong path when suggesting collective.portlet.fullview. i created it just recently for a customer project and fix some issues along the way as they arise. but i think, this will be a key portlet for me for upcoming plone projects, which use portlets. it just renders a content item with it's default view, that's the point.

do you use the github master branch checkout or the released version on pypi? please use the github source checkout! i'm planning to do a new release soon, if it also works for you.

regarding on how to display a slider gallery in the fullview portlet: you have to create a folder or collection somewhere, which has set it's default view to something displaying a slideshow. if you then select this folder or collection as content item in the fullview portlet, it should display it as expected. make sure, the "show content" checkbox is ticked (the purpose of this one is to allow the portlet to also show title and description only for teasers of articles).

**Comment by datakurre** [comment]
Ok. Solved. Most of the Plone default views does not seem to re-provide context-core -macro in their context-core -slot.
